### ISSUE TITLE
Do you have example inputs

### ISSUE THREAD

**Issue by sturgman** [mrmckain/PUG#2]
Hello!

I am helping a colleague run this script and I was wondering if you have any small sample inputs that you can add to the repository.

Thank you!

**Comment by mrmckain** [comment]
Demo data with results have been added.

Best,
Michael

**Comment by sturgman** [comment]
Thank you so much.

On Dec 9, 2018 4:56 PM, "Michael McKain" <notifications@github.com> wrote:

Demo data with results have been added.

Best,
Michael

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/mrmckain/PUG/issues/2#issuecomment-445575573>, or mute
the thread
